### PR TITLE
Multicore operation between entropy decode and rest of the reconstruc…

### PR DESCRIPTION
**Pull request by p-chirag**
…tion functionality in-case more than 2 task in single tile case

and some minor optimizations

### CODE REVIEW

**Comment by dariusz-f** [comment]
We will test this inside WebRTC

**Comment by dariusz-f** [comment]
We tested this code and it looks that output video have some artifacts (green and purple areas). We will try to check it closer and provide more details about this issue.

**Comment by dkozinski** [comment]
> 

After we did some tests, we noticed that artifacts appeared when the source video resolution was changing

**Comment by dkozinski** [comment]
One more notice.
After reverting changes that comes with PR#14 (back to commit efe6509781e68cacaff427d8645b81ad437537cd) all the artifacts disappeared.

**Comment by mpeg5** [comment]
@p-chirag 

Could you @dkozinski 's reports?

**Comment by p-chirag** [comment]
> @p-chirag
> 
> Could you check @dkozinski 's reports?

@mpeg5 sure I will look in to their findings

**Review by kpchoi — APPROVED** [review]
LGTM

**Pull request merged**
