### PR TITLE
Problem with similar functions with uvg266

### PR DESCRIPTION
**Pull request by Jamaika1**

### CODE REVIEW

**Comment by dkozinski** [comment]
You have made multiple commits with the same commit message. If the changes relate to the same problem, they should be included in one commit.

Another thing. You wrote in the commit message "Problem with similar functions with uvg266". Could you tell me more about that? What do you mean by "Problem with similar functions"? Which functions are problematic? What do you mean at all by the statement "similar functions"? Are you referring to functions with similar names or the same names?
Are there any naming conflicts between functions in xevd and uvg266?

The commit message should provide information that leaves no doubt about what the change does.

What you did was add static modifiers to some function names, which makes them not 'exported' and can only be used within the module in which they are defined. For other functions, you added the "xevd_" prefix. I assume you were trying to prevent potential naming conflicts.

**Comment by Jamaika1** [comment]
I failed to merge xeve, xevd, uvg266 as a plugin into ffmpeg  without dllexport.
GCC 11.3.1 doesn't allow this. Functions without `static` are treated as common xeve, xevd, uvg266.
Perhaps there is wonderful gcc function that circumvents this problem.
As for the uvg266 codec I had problem with the `alf_derive_classification function`.

**Comment by dariusz-f** [comment]
This change in general works correctly and when EVC is used if FFmpeg with this change all our test pass.
This change have to be integrated by using "Squash and merge"

**Review by dariusz-f — APPROVED** [review]

**Review by dkozinski — APPROVED** [review]
Looks good

**Pull request merged**
