### PR TITLE
Fix for crash when when get_extra_config is enabled

### PR DESCRIPTION
**Pull request by washish**
Modifications added to rectify the crash in the decoder, when get_extra_config is enabled.

### CODE REVIEW

**Review by dariusz-f — CHANGES_REQUESTED** [review]
The same change should be also applied in base profile

https://github.com/mpeg5/xevd/blob/1385ab56687b097cec2e7c86b65be08e58ede5ef/src_base/xevd.c#L2169

**Review by dkozinski — COMMENTED** [review]
It seems that the issue has been fixed at least for main profile. xevd_app no more crashes and work according to the expectation even if get_extra_config is uncommented.

**Comment by washish** [comment]
> It seems that the issue has been fixed at least for main profile. xevd_app no more crashes and work according to the expectation even if get_extra_config is uncommented.

@dkozinski added the fix for baseline code

**Review by dariusz-f — APPROVED** [review]
Now it works correctly

**Review by dkozinski — COMMENTED** [review]
It seems that the issue has been fixed

**Pull request merged**
